version: "3.7"

services:
  mysql:
    build: ./
    container_name: mysql
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root_test
      MYSQL_USER: elon
      MYSQL_PASSWORD: musk
      MYSQL_DATABASE: tesla
      MYSQL_REMOTE_ROOT_IP_ADDRESS: 172.26.0.1

volumes:
  data-test:
