version: "3"

services:
  mysql:
    image: omvk97/mysql
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root_test
      MYSQL_USER: elon
      MYSQL_PASSWORD: musk
      MYSQL_DATABASE: tesla
