version: "3.4"

services:
  mysql:
    image: omvk97/mysql
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: "monty"
      MYSQL_PASSWORD: "python"
      MYSQL_DATABASE: "db"
      MYSQL_ROOT_PASSWORD: "root_test"
